org: tkaewplik
app: aws-node-express-api
service: aws-node-express-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    DYNAMODB_CUSTOMER_TABLE: ${self:service}-customerTable-${sls:stage}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:Get*"
        - "dynamodb:Scan*"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
      Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-customerTable-${sls:stage}

functions:
  createCustomer:
    handler: createCustomer.createCustomer
    events:
      - httpApi:
          path: /create
          method: post
  getCustomers:
    handler: getCustomers.getCustomers
    events: 
      - httpApi:
          path: /get
          method: get
  getWebpage:
    handler: getCustomers.getWebpage
    events: 
      - httpApi:
          path: /web
          method: get
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
  
# todo: use custom!
custom:
  dynamodb:
  # If you only want to use DynamoDB Local in some stages, declare them here
    migrate: true
    stages:
      - dev
    start:
      docker: true
      port: 8000
      inMemory: true
      migrate: true
      seed: true
      convertEmptyValues: true
    # Uncomment only if you already have a DynamoDB running locally
    # noStart: true

resources:
  Resources:
    CustomerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: primary_key
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: primary_key
            KeyType: HASH
        TableName: ${self:service}-customerTable-${sls:stage}
plugins:
  - serverless-offline
  - serverless-dynamodb-local
